### ISSUE TITLE
 error in function render not enough space

### ISSUE THREAD

**Issue by simonlearnscoding** [RaafatTurki/corn.nvim#13]
sometimes I get spammed with an error saying error in function render not enough space

![Uploading grafik.png…]()

**Comment by simonlearnscoding** [comment]
![grafik](https://github.com/RaafatTurki/corn.nvim/assets/40177876/840e157f-ad03-4bc2-b6ec-a1972cacffa5)

**Comment by RaafatTurki** [comment]
Hi! I need more information to work with here
A minimal reproduction would be best .. or anything better than a screenshot in German ahaha

**Comment by vunhatchuong** [comment]
I have the same problem ?:
![image](https://github.com/RaafatTurki/corn.nvim/assets/20581504/78cd26e1-6fc4-4ca6-83ec-0da6dd0ced11)

corn settings:

```lua
return {
    "RaafatTurki/corn.nvim",
    event = "LspAttach",
    opts = {
        border_style = "rounded",
        on_toggle = function(is_hidden)
            vim.diagnostic.config({
                virtual_text = not vim.diagnostic.config().virtual_text,
            })
        end,
        item_preprocess_func = function(item)
            return item
        end,
    },
    config = function(_, opts)
        local corn = require("corn")
        -- ensure virtual_text diags are disabled
        vim.diagnostic.config({ virtual_text = false })
        corn.setup(opts)
    end,
}
```
I don't know what information you need but my nvim config is in my repo, [lsp configs](https://github.com/vunhatchuong/.dotfiles/blob/main/nvim/lua/plugins/lsp/init.lua).

### When

The same error would pop up 3, 4 times in the middle of me writing code.

For example, I'm in the middle of writing this class, it would pop up because I "forget" to have a class body or  `pass` keyword.
```python
class ServiceResponse(ResponseBase[T]):
```
