### ISSUE TITLE
Disable specific diagnostics?

### ISSUE THREAD

**Issue by JustBarnt** [RaafatTurki/corn.nvim#9]
I currently over write the diagnostics that get show with the LSP, but for what ever reason Corn doesn't seem to be respecting that, and I still see `Hint` type diagnostics. How can I disable that?
```lua
-- Override LSP diagnostics support if its supported.
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics, {
        signs = { severity_limit = "Warning" },
        underline = { severity_limit = "Warning" },
        virtual_text = false,
    }
)
```

**Comment by RaafatTurki** [comment]
Hi, Corn uses the `vim.diagnostic.get` API to fetch LSP diags and that doesn't respect severity limiting the way you've shown above.

Regardless, in the spirit of customization the new update 77f0a812a0307ab8ecf0ed4e0b5a8864fb56a0ab introduces the config option `blacklisted_severities` which allows the user to pick-and-choose which severities to disable rather than setting a linear limit.
